name: build
on: [push, pull_request, workflow_dispatch]

jobs:
  windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout exgine
        uses: actions/checkout@v4
        with:
          path: exgine
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake clang llvm
          sudo apt install libwayland-dev libxkbcommon-dev xorg-dev
          sudo apt install -y mingw-w64 mingw-w64-tools ninja-build libpthread-stubs0-dev
      - name: Configure
        run: cmake -Bbuild -Hexgine -DCMAKE_TOOLCHAIN_FILE=windows.cmake -DCMAKE_INSTALL_PREFIX=$PWD/install
      - name: Build
        run: cmake --build build --config Release -j2
      - uses: actions/upload-artifact@v4
        with:
          name: exgine_windows-x64
          path: |
            build/starter.exe
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout exgine
        uses: actions/checkout@v4
        with:
          path: exgine
          submodules: 'recursive'
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake
          sudo apt install libwayland-dev libxkbcommon-dev xorg-dev
      - name: Configure
        run: cmake -Bbuild -Hexgine -DCMAKE_INSTALL_PREFIX=$PWD/install
      - name: Build
        run: cmake --build build --config Release -j2
      - uses: actions/upload-artifact@v4
        with:
          name: exgine_linux-x64
          path: |
            build/starter
